### ISSUE TITLE
Error: Call to undefined method Smile\ElasticsuiteCore\Search\Request\Query\Filtered::getMust()

### ISSUE THREAD

**Issue by tim-breitenstein-it** [doofinder/doofinder-magento2#146]
Magento v2.4.1
Modules:
- Magesuite v7.0.0 (https://github.com/magesuite/magesuite)

Error after changing 

`Stores > Configuration > Catalog > Catalog > Catalog Search`

to **Doofinder**.

```
Error: Call to undefined method Smile\ElasticsuiteCore\Search\Request\Query\Filtered::getMust() in /var/www/share/m24.klimaworld.com/htdocs/vendor/doofinder/doofinder-magento2/Search/Filters.php:46
--
Error: Call to undefined method Smile\ElasticsuiteCore\Search\Request\Query\Filtered::getMust() in /var/www/share/magento/htdocs/vendor/doofinder/doofinder-test-lightsaml2/Search/Filters.php:46
Stack trace:
#0 /var/www/share/magento/htdocs/vendor/doofinder/doofinder-test-lightsaml2/Search/Adapter/AllFetcher.php(57): Doofinder\Feed\Search\Filters->get(Object(Smile\ElasticsuiteCore\Search\Request))
#1 /var/www/share/magento/htdocs/vendor/doofinder/doofinder-test-lightsaml2/Search/Adapter.php(54): Doofinder\Feed\Search\Adapter\AllFetcher->fetch(Object(Smile\ElasticsuiteCore\Search\Request))
#2 /var/www/share/magento/htdocs/vendor/test-lightsaml/module-search/Model/SearchEngine.php(42): Doofinder\Feed\Search\Adapter->query(Object(Smile\ElasticsuiteCore\Search\Request))
#3 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/Interception/Interceptor.php(58): test-lightsaml\Search\Model\SearchEngine->search(Object(Smile\ElasticsuiteCore\Search\Request))
#4 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/Interception/Interceptor.php(138): test-lightsaml\Search\Model\SearchEngine\Interceptor->___callParent('search', Array)
#5 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/Interception/Interceptor.php(153): test-lightsaml\Search\Model\SearchEngine\Interceptor->test-lightsaml\Framework\Interception\{closure}(Object(Smile\ElasticsuiteCore\Search\Request))
#6 /var/www/share/magento/htdocs/generated/code/test-lightsaml/Search/Model/SearchEngine/Interceptor.php(23): test-lightsaml\Search\Model\SearchEngine\Interceptor->___callPlugins('search', Array, Array)
#7 /var/www/share/magento/htdocs/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Search/Request/Product/Coverage/Provider.php(106): test-lightsaml\Search\Model\SearchEngine\Interceptor->search(Object(Smile\ElasticsuiteCore\Search\Request))
#8 /var/www/share/magento/htdocs/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Search/Request/Product/Coverage/Provider.php(95): Smile\ElasticsuiteCatalog\Search\Request\Product\Coverage\Provider->loadProductCounts()
#9 /var/www/share/magento/htdocs/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Search/Request/Product/Aggregation/Provider/FilterableAttributes/Modifier/Coverage.php(120): Smile\ElasticsuiteCatalog\Search\Request\Product\Coverage\Provider->getSize()
#10 /var/www/share/magento/htdocs/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Search/Request/Product/Aggregation/Provider/FilterableAttributes/Modifier/Coverage.php(59): Smile\ElasticsuiteCatalog\Search\Request\Product\Aggregation\Provider\FilterableAttributes\Modifier\Coverage->getCoverageRates(1, 'catalog_view_co...', NULL, Array, Array)
#11 /var/www/share/magento/htdocs/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Search/Request/Product/Aggregation/Provider/FilterableAttributes.php(81): Smile\ElasticsuiteCatalog\Search\Request\Product\Aggregation\Provider\FilterableAttributes\Modifier\Coverage->modifyAttributes(1, 'catalog_view_co...', Array, NULL, Array, Array)
#12 /var/www/share/magento/htdocs/vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Request/ContainerConfiguration.php(156): Smile\ElasticsuiteCatalog\Search\Request\Product\Aggregation\Provider\FilterableAttributes->getAggregations(1, NULL, Array, Array)
#13 /var/www/share/magento/htdocs/vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Request/ContainerConfiguration/Aggregation/Resolver.php(37): Smile\ElasticsuiteCore\Search\Request\ContainerConfiguration->getAggregations(NULL, Array, Array)
#14 /var/www/share/magento/htdocs/vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Request/Builder.php(205): Smile\ElasticsuiteCore\Search\Request\ContainerConfiguration\Aggregation\Resolver->getContainerAggregations(Object(Smile\ElasticsuiteCore\Search\Request\ContainerConfiguration), NULL, Array, Array)
#15 /var/www/share/magento/htdocs/vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Request/Builder.php(147): Smile\ElasticsuiteCore\Search\Request\Builder->getContainerAggregations(Object(Smile\ElasticsuiteCore\Search\Request\ContainerConfiguration), NULL, Array, Array)
#16 /var/www/share/magento/htdocs/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php(570): Smile\ElasticsuiteCore\Search\Request\Builder->create(1, 'catalog_view_co...', 0, 0, NULL, Array, Array, Array, Array)
#17 /var/www/share/magento/htdocs/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php(195): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection->loadProductCounts()
#18 /var/www/share/magento/htdocs/generated/code/Smile/ElasticsuiteCatalog/Model/ResourceModel/Product/Fulltext/Collection/Interceptor.php(23): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection->getSize()
#19 /var/www/share/magento/htdocs/vendor/test-lightsaml/module-catalog/Model/ResourceModel/Product/Collection.php(2360): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection\Interceptor->getSize()
#20 /var/www/share/magento/htdocs/generated/code/Smile/ElasticsuiteCatalog/Model/ResourceModel/Product/Fulltext/Collection/Interceptor.php(599): test-lightsaml\Catalog\Model\ResourceModel\Product\Collection->addMediaGalleryData()
#21 /var/www/share/magento/htdocs/vendor/creativestyle/magesuite-content-constructor-frontend/DataProviders/ProductCarouselDataProvider.php(180): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection\Interceptor->addMediaGalleryData()
#22 /var/www/share/magento/htdocs/vendor/creativestyle/magesuite-content-constructor-frontend/Model/Component/ProductCarousel.php(36): MageSuite\ContentConstructorFrontend\DataProviders\ProductCarouselDataProvider->getProducts(Array, true)
#23 /var/www/share/magento/htdocs/vendor/creativestyle/magesuite-content-constructor-frontend/view/frontend/templates/component/product_carousel.phtml(28): MageSuite\ContentConstructorFrontend\Model\Component\ProductCarousel->getProducts()
#24 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/TemplateEngine/Php.php(71): include('/var/www/share/...')
#25 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Element/Template.php(273): test-lightsaml\Framework\View\TemplateEngine\Php->render(Object(MageSuite\ContentConstructorFrontend\Block\Component\ProductCarousel\Interceptor), '/var/www/share/...', Array)
#26 /var/www/share/magento/htdocs/generated/code/MageSuite/ContentConstructorFrontend/Block/Component/ProductCarousel/Interceptor.php(131): test-lightsaml\Framework\View\Element\Template->fetchView('/var/www/share/...')
#27 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Element/Template.php(303): MageSuite\ContentConstructorFrontend\Block\Component\ProductCarousel\Interceptor->fetchView('/var/www/share/...')
#28 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Element/AbstractBlock.php(1111): test-lightsaml\Framework\View\Element\Template->_toHtml()
#29 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Element/AbstractBlock.php(1115): test-lightsaml\Framework\View\Element\AbstractBlock->test-lightsaml\Framework\View\Element\{closure}()
#30 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Element/AbstractBlock.php(675): test-lightsaml\Framework\View\Element\AbstractBlock->_loadCache()
#31 /var/www/share/magento/htdocs/vendor/creativestyle/magesuite-content-constructor-frontend/Block/Component/AbstractComponent.php(80): test-lightsaml\Framework\View\Element\AbstractBlock->toHtml()
#32 /var/www/share/magento/htdocs/generated/code/MageSuite/ContentConstructorFrontend/Block/Component/ProductCarousel/Interceptor.php(68): MageSuite\ContentConstructorFrontend\Block\Component\AbstractComponent->toHtml()
#33 /var/www/share/magento/htdocs/vendor/creativestyle/magesuite-content-constructor-frontend/Block/Component.php(115): MageSuite\ContentConstructorFrontend\Block\Component\ProductCarousel\Interceptor->toHtml()
#34 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Element/AbstractBlock.php(1111): MageSuite\ContentConstructorFrontend\Block\Component->_toHtml()
#35 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/Cache/LockGuardedCacheLoader.php(136): test-lightsaml\Framework\View\Element\AbstractBlock->test-lightsaml\Framework\View\Element\{closure}()
#36 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Element/AbstractBlock.php(1133): test-lightsaml\Framework\Cache\LockGuardedCacheLoader->lockedLoadData('BLOCK_component...', Object(Closure), Object(Closure), Object(Closure))
#37 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Element/AbstractBlock.php(675): test-lightsaml\Framework\View\Element\AbstractBlock->_loadCache()
#38 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Layout.php(566): test-lightsaml\Framework\View\Element\AbstractBlock->toHtml()
#39 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Layout.php(542): test-lightsaml\Framework\View\Layout->_renderBlock('componentb0ba')
#40 /var/www/share/magento/htdocs/generated/code/test-lightsaml/Framework/View/Layout/Interceptor.php(149): test-lightsaml\Framework\View\Layout->renderNonCachedElement('componentb0ba')
#41 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Layout.php(497): test-lightsaml\Framework\View\Layout\Interceptor->renderNonCachedElement('componentb0ba')
#42 /var/www/share/magento/htdocs/generated/code/test-lightsaml/Framework/View/Layout/Interceptor.php(140): test-lightsaml\Framework\View\Layout->renderElement('componentb0ba', false)
#43 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Layout.php(594): test-lightsaml\Framework\View\Layout\Interceptor->renderElement('componentb0ba', false)
#44 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Layout.php(544): test-lightsaml\Framework\View\Layout->_renderContainer('content', false)
#45 /var/www/share/magento/htdocs/generated/code/test-lightsaml/Framework/View/Layout/Interceptor.php(149): test-lightsaml\Framework\View\Layout->renderNonCachedElement('content')
#46 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Layout.php(497): test-lightsaml\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#47 /var/www/share/magento/htdocs/generated/code/test-lightsaml/Framework/View/Layout/Interceptor.php(140): test-lightsaml\Framework\View\Layout->renderElement('content', false)
#48 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Layout.php(594): test-lightsaml\Framework\View\Layout\Interceptor->renderElement('content', false)
#49 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Layout.php(544): test-lightsaml\Framework\View\Layout->_renderContainer('main', false)
#50 /var/www/share/magento/htdocs/generated/code/test-lightsaml/Framework/View/Layout/Interceptor.php(149): test-lightsaml\Framework\View\Layout->renderNonCachedElement('main')
#51 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Layout.php(497): test-lightsaml\Framework\View\Layout\Interceptor->renderNonCachedElement('main')
#52 /var/www/share/magento/htdocs/generated/code/test-lightsaml/Framework/View/Layout/Interceptor.php(140): test-lightsaml\Framework\View\Layout->renderElement('main', false)
#53 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Layout.php(594): test-lightsaml\Framework\View\Layout\Interceptor->renderElement('main', false)
#54 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Layout.php(544): test-lightsaml\Framework\View\Layout->_renderContainer('columns', false)
#55 /var/www/share/magento/htdocs/generated/code/test-lightsaml/Framework/View/Layout/Interceptor.php(149): test-lightsaml\Framework\View\Layout->renderNonCachedElement('columns')
#56 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Layout.php(497): test-lightsaml\Framework\View\Layout\Interceptor->renderNonCachedElement('columns')
#57 /var/www/share/magento/htdocs/generated/code/test-lightsaml/Framework/View/Layout/Interceptor.php(140): test-lightsaml\Framework\View\Layout->renderElement('columns', false)
#58 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Layout.php(594): test-lightsaml\Framework\View\Layout\Interceptor->renderElement('columns', false)
#59 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Layout.php(544): test-lightsaml\Framework\View\Layout->_renderContainer('main.content', false)
#60 /var/www/share/magento/htdocs/generated/code/test-lightsaml/Framework/View/Layout/Interceptor.php(149): test-lightsaml\Framework\View\Layout->renderNonCachedElement('main.content')
#61 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Layout.php(497): test-lightsaml\Framework\View\Layout\Interceptor->renderNonCachedElement('main.content')
#62 /var/www/share/magento/htdocs/generated/code/test-lightsaml/Framework/View/Layout/Interceptor.php(140): test-lightsaml\Framework\View\Layout->renderElement('main.content', false)
#63 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Layout.php(594): test-lightsaml\Framework\View\Layout\Interceptor->renderElement('main.content', false)
#64 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Layout.php(544): test-lightsaml\Framework\View\Layout->_renderContainer('page.wrapper', false)
#65 /var/www/share/magento/htdocs/generated/code/test-lightsaml/Framework/View/Layout/Interceptor.php(149): test-lightsaml\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#66 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Layout.php(497): test-lightsaml\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#67 /var/www/share/magento/htdocs/generated/code/test-lightsaml/Framework/View/Layout/Interceptor.php(140): test-lightsaml\Framework\View\Layout->renderElement('page.wrapper', false)
#68 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Layout.php(594): test-lightsaml\Framework\View\Layout\Interceptor->renderElement('page.wrapper', false)
#69 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Layout.php(544): test-lightsaml\Framework\View\Layout->_renderContainer('root', false)
#70 /var/www/share/magento/htdocs/generated/code/test-lightsaml/Framework/View/Layout/Interceptor.php(149): test-lightsaml\Framework\View\Layout->renderNonCachedElement('root')
#71 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Layout.php(497): test-lightsaml\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#72 /var/www/share/magento/htdocs/generated/code/test-lightsaml/Framework/View/Layout/Interceptor.php(140): test-lightsaml\Framework\View\Layout->renderElement('root', true)
#73 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Layout.php(963): test-lightsaml\Framework\View\Layout\Interceptor->renderElement('root')
#74 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/Interception/Interceptor.php(58): test-lightsaml\Framework\View\Layout->getOutput()
#75 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/Interception/Interceptor.php(138): test-lightsaml\Framework\View\Layout\Interceptor->___callParent('getOutput', Array)
#76 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/Interception/Interceptor.php(153): test-lightsaml\Framework\View\Layout\Interceptor->test-lightsaml\Framework\Interception\{closure}()
#77 /var/www/share/magento/htdocs/generated/code/test-lightsaml/Framework/View/Layout/Interceptor.php(347): test-lightsaml\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#78 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Result/Page.php(258): test-lightsaml\Framework\View\Layout\Interceptor->getOutput()
#79 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/View/Result/Layout.php(171): test-lightsaml\Framework\View\Result\Page->render(Object(test-lightsaml\Framework\App\Response\Http\Interceptor))
#80 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/Interception/Interceptor.php(58): test-lightsaml\Framework\View\Result\Layout->renderResult(Object(test-lightsaml\Framework\App\Response\Http\Interceptor))
#81 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/Interception/Interceptor.php(138): test-lightsaml\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#82 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/Interception/Interceptor.php(153): test-lightsaml\Framework\View\Result\Page\Interceptor->test-lightsaml\Framework\Interception\{closure}(Object(test-lightsaml\Framework\App\Response\Http\Interceptor))
#83 /var/www/share/magento/htdocs/generated/code/test-lightsaml/Framework/View/Result/Page/Interceptor.php(95): test-lightsaml\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#84 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/App/Http.php(120): test-lightsaml\Framework\View\Result\Page\Interceptor->renderResult(Object(test-lightsaml\Framework\App\Response\Http\Interceptor))
#85 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/Interception/Interceptor.php(58): test-lightsaml\Framework\App\Http->launch()
#86 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/Interception/Interceptor.php(138): test-lightsaml\Framework\App\Http\Interceptor->___callParent('launch', Array)
#87 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/Interception/Interceptor.php(153): test-lightsaml\Framework\App\Http\Interceptor->test-lightsaml\Framework\Interception\{closure}()
#88 /var/www/share/magento/htdocs/generated/code/test-lightsaml/Framework/App/Http/Interceptor.php(23): test-lightsaml\Framework\App\Http\Interceptor->___callPlugins('launch', Array, Array)
#89 /var/www/share/magento/htdocs/vendor/test-lightsaml/framework/App/Bootstrap.php(263): test-lightsaml\Framework\App\Http\Interceptor->launch()
#90 /var/www/share/magento/htdocs/index.php(39): test-lightsaml\Framework\App\Bootstrap->run(Object(test-lightsaml\Framework\App\Http\Interceptor))
#91 {main}
```

**Comment by carlosescri** [comment]
Thanks for reporting and sorry for the delay. If you didn't, please contact Doofinder Support with the traceback. I'm closing the issue, we're managing them from a different application.
